# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  installation:
    runs-on: ubuntu-20.04
    steps:
      - name: installationSwift
        uses: fwal/setup-swift@v1
        with:
          swift-version: "5.3.0"
  
  unitTests:
    needs: installation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: swift build
      - run: swift test
        
  systemTests:
    needs: installation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: swift build
      - run: bash Test.sh         